### ISSUE TITLE
Work out what our due dates actually are

### ISSUE THREAD

**Issue by jobcurtis** [jobcurtis/smartcare#1]
According to my.uwe Week 7 was 31/08/2020

**Comment by RyanWilliams99** [comment]
I Emailed Mehmet

**Comment by RyanWilliams99** [comment]
Please find the below is the dates  of the weeks require coalition of Sprints. 

Week 7 : 30th Nov - 4th Dec
Week 9 : 14th - 18th Dec
Week 11: 18th - 22nd Jan

Each group will do presentation during their practical day subject to a schedule to be released prior to that week, accordingly.
